language: java
jdk:
  - openjdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - ./gradlew --info check
after_success:
  - ./gradlew jacocoCoverallsReport coveralls
